### ISSUE TITLE
Log in 404 error

### ISSUE THREAD

**Issue by unoukujou** [DesarrolloAntonio/Shiori-Android-Client#20]
![20240217_imgpipe_0](https://github.com/DesarrolloAntonio/Shiori-Android-Client/assets/82226957/93eee2e8-b9ac-4cb5-a89b-c854466791d0)

Log in with pagekeeper gives this error.

Log in is working fine via regular browser.

**Comment by thagoat** [comment]
Yes. Same

**Comment by DesarrolloAntonio** [comment]
I have a test server with these credentials

User: testing
pass: shiori
url: http://144.24.183.231:8086/

Can you try those credentials to see if you're still getting the error?

**Comment by unoukujou** [comment]
> I have a test server with these credentials
> 
> User: testing pass: shiori url: http://144.24.183.231:8086/
> 
> Can you try those credentials to see if you're still getting the error?

Working fine with the test server.

But still getting 404 error on my own local server. But my local server works fine via browser (only pagekeeper not working for some reason)

**Comment by OPerepadia** [comment]
@DesarrolloAntonio Thank you for providing the test server. May I know what version of shiori you have deployed there?

My observation is that the 1.5.x versions are working fine, but starting with version 1.6.x started getting 404 error.
I believe this is same issue as mentioned here https://github.com/go-shiori/shiori-web-ext/issues/61

**Comment by graphixillusion** [comment]
I can confirm: with server 1.5.x the app works; with server version 1.6.x i get 404 error too. Actually i get a session expire too everytime i open the app, i don't know if it's related

**Comment by DesarrolloAntonio** [comment]
> I can confirm: with server 1.5.x the app works; with server version 1.6.x i get 404 error too. Actually i get a session expire too everytime i open the app, i don't know if it's related

Thanks, in next release it will be fixed

**Comment by DesarrolloAntonio** [comment]
I have released a new version, but this bug is not fixed in this version.

**Comment by DesarrolloAntonio** [comment]
New version 1.1 released where the problem is solved, if not, let me know.

**Comment by graphixillusion** [comment]
@DesarrolloAntonio I confirm: it works with 1.11, no more 404 error. I still have problems with session expired.

**Comment by yonas** [comment]
1.11 works for me as well.

**Comment by ngocanhtve** [comment]
How do I have an account to use this application?

**Comment by ngocanhtve** [comment]
How do I have an account to use this application?

**Comment by graphixillusion** [comment]
> How do I have an account to use this application?

you need to selfhost your own server.

**Comment by DesarrolloAntonio** [comment]
> @DesarrolloAntonio I confirm: it works with 1.11, no more 404 error with the last 1.6.0.rc7. I still have problems with session expired.

Can you confirm if it could be because the server restarts?

**Comment by DesarrolloAntonio** [comment]
> > Can you confirm if it could be because the server restarts?
> 
> Yep you are right: if the server restarts the session expired error will shows up in the app.

You can add the SHIORI_HTTP_SECRET_KEY environment key
https://github.com/go-shiori/shiori/issues/782

**Comment by ngocanhtve** [comment]
> you need to selfhost your own server.

This app wants to create complex problems. 🤣

**Comment by DesarrolloAntonio** [comment]
> This app wants to create complex problems

Following the tutorial, it is not difficult to create the server side.
https://github.com/go-shiori/shiori

**Comment by ngocanhtve** [comment]
Must set up an entire server to serve only one application?

**Comment by DesarrolloAntonio** [comment]
> Must set up an entire server to serve only one application?
> 
> Those who cannot afford a 24/7 power-hungry server will not be able to use the application?

Indeed, the requirement to set up a dedicated server for this application stems from its self-hosted nature, which is standard for such projects. This approach offers greater control and privacy but may not be suitable for everyone due to the resources needed for a 24/7 operation. We understand this concern and appreciate your feedback.

**Comment by ngocanhtve** [comment]
While I'm also very interested in open source, privacy, I unfortunately do not and will never want to self-host. Extreme privacy leads to more complex problems that need to be solved.
